### ISSUE TITLE
Packing with webpack causes an error.

### ISSUE THREAD

**Issue by nicholascioli** [pwstegman/bcijs#2]
When attempting to pack this code for use on a browser-only solution, webbci's dependence on node-osc causes webpack to error due to node-only dependencies.

```
ERROR in ./node_modules/node-osc/lib/safeDgram.js
Module not found: Error: Can't resolve 'dgram' in './node_modules/node-osc/lib'
 @ ./node_modules/node-osc/lib/safeDgram.js 3:12-28
 @ ./node_modules/node-osc/lib/Server.js
 @ ./node_modules/node-osc/lib/index.js
 @ ./node_modules/webbci/lib/network.js
 @ ./node_modules/webbci/index.js
```

If you don't expect for this code to run on the browser side only, then this is probably expected behavior.

**Comment by pwstegman** [comment]
OSC doesn't work in the browser. I'll work on adding safe guards with warning messages if it's attempted. Is this error just being thrown from within the browser when OSC methods are directly called, or is it preventing a web build entirely?

**Comment by pwstegman** [comment]
I added `bcijs/browser.js` which loads only browser compatible methods. If building with webpack you can use this require statement to prevent any issues:

```javascript
const bci = require('bcijs/browser.js');
```
